ingress-nginx:
  controller:
    replicaCount: 1
    service:
      type: NodePort
    admissionWebhooks:
      enabled: false

metrics-server:
  replicas: 1
  args:
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname


