apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: management-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ghshenavar/kubernetes-cluster-management.git
    targetRevision: main
    path: charts/management
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ghshenavar/kubernetes-cluster-management.git
    targetRevision: main
    path: charts/sample-app
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ghshenavar/kubernetes-cluster-management.git
    targetRevision: main
    path: charts/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

