replicaCount: 1

image:
  repository: gcr.io/kuar-demo/kuard-amd64
  tag: "1"
  pullPolicy: Always

service:
  port: 80
  targetPort: 8080

ingress:
  host: example.example.com
  className: nginx
  tls:
    secretName: quickstart-example-tls
  annotations: {}
    # cert-manager.io/issuer: "letsencrypt-staging"
