replicaCount: 1

image:
  repository: nginx
  tag: "latest"
  pullPolicy: Always

service:
  port: 80
  targetPort: 80

ingress:
  host: example.example.com
  className: nginx
  tls:
    secretName: quickstart-example-tls
  annotations: {}
    # cert-manager.io/issuer: "letsencrypt-staging"
